### ISSUE TITLE
I am so confused with the insertion method.

### ISSUE THREAD

**Issue by ggaaooppeenngg** [derekparker/rbtree#1]
Your code is different with the normal iterate insertion method which I found in [wikipedia](http://en.wikipedia.org/wiki/Red%E2%80%93black_tree),which considers a lot of cases,and it seems that your code is bottom-up insertion,I found relevant [post](http://www.eternallyconfuzzled.com/tuts/datastructures/jsw_tut_rbtree.aspx),but it also considers 3 cases 
1.  (left==red&&right==red)
2.  (left==red&&left.left==red,or right==red&&right.right==red)
3.  (left==red&&left.right==red,or right==red&&right.left==red)
But I could not figure out how you insertion works,it really made me curious.How do these 3 conditions avoid red violation?

```

    if !isRed(n.left) && isRed(n.right) {
        n = rotateLeft(n)
    }

    if isRed(n.left) && isRed(n.left.left) {
        n = rotateRight(n)
    }

    if isRed(n.left) && isRed(n.right) {
        changeColors(n)
    }
```

**Comment by derekparker** [comment]
What the code is doing is an insertion and then a rebalancing on the way back up to the root. Since the insert is recursive we are able to balance the tree after the function calls return. Essentially, once we insert our new node, that function will return, and a rebalancing will occur, then that function will return and rebalance, so on and so forth.

Red links (nodes) lean left, and the balancing ensures that property. Does this help answer your question at all? I'm also all ears for any improvement / alternate approach. This data structure is adapted from Algorithms Fourth Edition by Robert Sedgewick and Kevin Wayne.

**Comment by ggaaooppeenngg** [comment]
Thx!This algorithm source helps me a lot to understand the implementation,it is a variant from the 2-3 tree,and red link always leans left.This structure suffices red  black tree properties but not include all the possible red black tree structures,like tree (R(B)),if a R add to right,(R(B)R),it is ok,but will turn into (B(B)B).This is really a nice implementation,since the insertion code is rather less,and logic is clear.

**Comment by derekparker** [comment]
No problem, glad I could help explain. The left leaning convention really does simplify the code a lot.
